### ISSUE TITLE
A question: Which arabic language?

### ISSUE THREAD

**Issue by eklem** [stopwords-iso/stopwords-ar#1]
Hi @genediazjr,
I'm using the stopword list for Arabic language in the [stopword](https://github.com/fergiemcdowall/stopword) module. At some point I've marked it as `Arabic, Modern standard?`. I see that it may not be correct. We're changing the language codes to ISO-939-3 from ISO-939-1, I looked at this [table containing all the Arabic languages and codes](https://iso639-3.sil.org/code_tables/639/data?title=&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=Arabic&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=All&items_per_page=200) and I'm wondering which is the most correct code for `stopword-ar`?

I'm guessing it's
`ara | ar | Arabic | Macrolanguage`,

but I could be wrong and it's maybe
`arb |   |   | Standard Arabic | Individual`?

Anyway, greatful for any answer I can get, and a great list of words!

**Comment by genediazjr** [comment]
it would be 
```ara | ar | Arabic | Macrolanguage```

**Comment by eklem** [comment]
Thank you!
